services:
  - type: web
    name: attacker-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL
        value: https://attacker-bankend.onrender.com/api/v1
      - key: VITE_SOCKET_URL
        value: https://attacker-bankend.onrender.com
      - key: VITE_FRONTEND_URL
        value: https://attacker-frontend-1.onrender.com
